<?php
/**
 * @package WordPress
 * @subpackage LaMula Theme
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head profile="http://gmpg.org/xfn/11">

<!-- Meta Properties -->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="generator" content="WordPress 2.7" />

<meta name="description" content="" />
<!-- Add Keywords, etc.-->

<title>  </title>

<!-- Add Stylesheets for screen,print,etc.-->
<link rel="stylesheet" type="text/css" media="screen" href="http://lamula.pe/wp-content/themes/pressbox-premium/style.css" />
<link rel="stylesheet" type="text/css" media="print" href="http://lamula.pe/wp-content/themes/pressbox-premium/styles/print.css" />
<!--[if gt IE 6]><link rel="stylesheet" type="text/css" href="http://lamula.pe/wp-content/themes/pressbox-premium/styles/iehacks.css" /><![endif]-->
<link rel="stylesheet" type="text/css" media="screen" href="http://lamula.pe/wp-content/themes/pressbox-premium/userstyles.css" />
<!--[if lt IE 7]> <style>div.magazine-thing * {width:38.39em; overflow:hidden;}</style> <![endif]-->

<!-- Blog Specific Stuff like rss and pingback.-->
<link rel="alternate" type="application/rss+xml" title=" RSS Feed" href="http://lamula.pe/feed/" />
<link rel="pingback" href="http://lamula.pe/xmlrpc.php" />

<link rel="stylesheet" href="<?php bloginfo('stylesheet_url'); ?>" type="text/css" media="screen" />


<!-- Scripts (mostly plugins, etc.)-->


<!-- Generated-->
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://lamula.pe/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://lamula.pe/wp-includes/wlwmanifest.xml" /> 
<script type='text/javascript' src='http://lamula.pe/wp-content/plugins/vipers-video-quicktags/resources/swfobject.js?ver=2.1'></script>
<meta name="generator" content="WordPress 2.7" />


<!-- Start Of Script Generated By WP-PostRatings 1.40 -->
<script type="text/javascript">
/* <![CDATA[ */
	var ratings_plugin_url = 'http://lamula.pe/wp-content/plugins/wp-postratings';
	var ratings_ajax_url = 'http://lamula.pe/wp-content/plugins/wp-postratings/wp-postratings.php';
	var ratings_text_wait = 'Please rate only 1 post at a time.';
	var ratings_image = 'stars';
	var ratings_image_ext = 'gif';
	var ratings_max = 5;
	var ratings_mouseover_image = new Image();
	ratings_mouseover_image.src = ratings_plugin_url + "/images/" + ratings_image + "/rating_over.gif";
	var ratings_show_loading = 1;
	var ratings_show_fading = 1;
	var ratings_custom = 0;
/* ]]> */
</script>
<script type='text/javascript' src='http://lamula.pe/wp-includes/js/tw-sack.js?ver=1.6.1'></script>
<script type='text/javascript' src='http://lamula.pe/wp-content/plugins/wp-postratings/postratings-js-packed.js?ver=1.40'></script>
<link rel='stylesheet' href='http://lamula.pe/wp-content/plugins/wp-postratings/postratings-css.css?ver=1.40' type='text/css' media='all' />
<!-- End Of Script Generated By WP-PostRatings 1.40 -->
<!-- Viper's Video Quicktags v6.1.21 | http://www.viper007bond.com/wordpress-plugins/vipers-video-quicktags/ -->
<style type="text/css">
.vvqbox { display: block; max-width: 100%; visibility: visible !important; margin: 10px auto; } .vvqbox img { max-width: 100%; height: 100%; } .vvqbox object { max-width: 100%; } 
</style>
<script type="text/javascript">
// <![CDATA[
	var vvqflashvars = {};
	var vvqparams = { wmode: "opaque", allowfullscreen: "true" };
	var vvqattributes = {};
	var vvqexpressinstall = "http://lamula.pe/wp-content/plugins/vipers-video-quicktags/resources/expressinstall.swf";
// ]]>
</script>

<style>

</style>
</head>
